version: 0.1.1
name: Task Board Documentation
title: Task Board Documentation
description: This is an detailed documentation for the Task Board plugin of Obsidian.
repository: https://github.com/tu2-atmanand/Task-Board-Docs
github_username: tu2-atmanand
site_branch: main
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Atmanand Gauns
repo_url: "https://github.com/tu2-atmanand/task-board-docs"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist

logo: "https://github.com/tu2-atmanand/task-board-docs/assets/ColoringKanbanBoard.png"
site_favicon: "https://github.com/tu2-atmanand/task-board-docs/assets/images/favicon.ico"

# Email and twitter are optional:
email: sanketgauns8@gmail.com
twitter_username: tu2-atmanand

favicon_path: /assets/images/favicon.ico

plugins:
    - jekyll-relative-links
    - jekyll-remote-theme
relative_links:
    enabled: true
    collections: true
include:
    - README.md
